input UpdateProjectInput {
  projectId: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  targetPrice: String!
  orderQuantities: [Int!]!
  comments: String
}

input UpdateProjectComponentInput {
  componentId: String!
  name: String!
  designIds: [String!]
  componentSpec: UpdateProjectComponentSpecInput!
}

input UpdateProjectComponentSpecInput {
  componentSpecId: String!
  productName: String!
  dimension: ProductDimensionInput!
  style: String
  boxStyle: String
  includeArtworkInQuote: Boolean

  numberOfPages: String

  purpose: String
  shape: String

  flute: String
  manufacturingProcess: String

  thickness: String
  color: String
  material: String
  materialSource: String
  postProcess: [PostProcessDetailInput!]
  finish: String

  outsideColor: String
  outsideMaterial: String
  outsideMaterialSource: String
  outsideFinish: String

  insideColor: String
  insideMaterial: String
  insideMaterialSource: String
  insideFinish: String
}

input UpdateProjectPermissionsInput {
  viewers: UpdateProjectPermissionsInputData!
  editors: UpdateProjectPermissionsInputData!
}

input UpdateProjectPermissionsInputData {
  userIds: [String]!
  projectId: String!
  permission: ProjectPermission!
}

type Mutation {
  updateProjectPermissions(data: UpdateProjectPermissionsInput!): Boolean!
  updateProject(data: UpdateProjectInput): Boolean
  updateProjectComponent(data: UpdateProjectComponentInput): Boolean
}
