input UpdateProjectInput {
  id: String!
  name: String!
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  components: [UpdateProjectComponentInput!]!
}

input UpdateProjectComponentInput {
  id: String!
  name: String!
  products: [String!]!
  dimension: String!
  postProcess: String!
}

input UpdateProjectPermissionsInput {
  viewers: UpdateProjectPermissionsInputData!
  editors: UpdateProjectPermissionsInputData!
}

input UpdateProjectPermissionsInputData {
  userIds: [String]!
  projectId: String!
  permission: ProjectPermission!
}

type Mutation {
  updateProjectPermissions(data: UpdateProjectPermissionsInput!): Boolean!
  # updateProject(data: UpdateProjectInput): Boolean
}
