input UpdateProjectInput {
  id: String!
  name: String!
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  components: [UpdateProjectComponentInput!]!
}

input UpdateProjectComponentInput {
  id: String!
  name: String!
  materials: [String!]!
  dimension: String!
  postProcess: String!
}

input UpdateProjectBidInput {
  id: String!
  comments: String!
  components: [UpdateProjectBidComponentInput!]!
}

input UpdateProjectBidComponentInput {
  id: String!
  quantityPrices: [QuantityPriceInput!]!
}

input UpdateProjectPermissionsInput {
  viewers: UpdateProjectPermissionsInputData!
  editors: UpdateProjectPermissionsInputData!
}

input UpdateProjectPermissionsInputData {
  userIds: [String]!
  projectId: String!
  permission: ProjectPermission!
}

input UpdateProjectBidPermissionsInput {
  viewers: UpdateProjectBidPermissionsInputData!
  editors: UpdateProjectBidPermissionsInputData!
}

input UpdateProjectBidPermissionsInputData {
  userIds: [String]!
  projectId: String!
  projectBidId: String!
  permission: ProjectPermission!
}

type Mutation {
  updateProjectPermissions(data: UpdateProjectPermissionsInput!): Boolean!
  updateProjectBidPermissions(data: UpdateProjectBidPermissionsInput!): Boolean!
  # updateProject(data: UpdateProjectInput): Boolean
  # updateProjectBid(data: UpdateProjectBidInput): Boolean
}
