input GetCompanyDetailInput {
  companyId: String!
}

input GetAllUsersWithinCompanyInput {
  companyId: String!
}

input GetCompanyPlanDetailInput {
  companyId: String!
}

type Query {
  getCompanyPlanDetail(data: GetCompanyPlanDetailInput!): CompanyPlanDetail!
  getCompanyDetail(data: GetCompanyDetailInput): CompanyDetail
}
