input QuantityPriceInput {
  quantity: Int!
  price: String!
}

input CreateProjectBidInput {
  userId: String!
  projectId: String!
  bidRemarkFileId: String
  components: [CreateProjectBidComponentInput!]!
}

input CreateProjectBidComponentInput {
  projectBidId: String
  projectComponentId: String!
  quantityPrices: [QuantityPriceInput!]!
  samplingFee: String!
  toolingFee: String
}

type Mutation {
  createProjectBid(data: CreateProjectBidInput!): Boolean!
  createProjectBidComponents(data: [CreateProjectBidComponentInput!]!): Boolean!
}
