type ProjectOverview {
  id: String!
  companyName: String!
  companyId: String!
  name: String!
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  products: [String!]!
  createdAt: String!
}
type ProjectDesign {
  fileName: String!
  url: String!
}

type Project {
  id: String!
  userId: String!
  companyId: String!
  companyName: String!
  name: String!
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  design: ProjectDesign
  status: String!
  components: [ProjectComponent!]!
  createdAt: String!
  updatedAt: String!
}

type ProjectComponent {
  id: String!
  projectId: String!
  name: String!
  product: String!
  createdAt: String!
  updatedAt: String!
}

enum ProjectPermission {
  OWNER
  VIEWER
  EDITOR
}

enum ProjectStatus {
  OPEN
  IN_PROGRESS
  CLOSED
}
