type ProjectOverview {
  id: String!
  companyId: String!
  name: String!
  companyName: String!
  category: String!
  deliveryDate: String!
  deliveryAddress: String!
  targetPrice: String!
  orderQuantities: [Int!]!
  products: [String!]!
  createdAt: Date!
}

type ProjectDesign implements FileInterface {
  fileId: String!
  filename: String!
  url: String!
}

interface ProjectInterface {
  id: String!
  userId: String!
  companyId: String!
  companyName: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  targetPrice: String!
  orderQuantities: [Int!]!
  status: ProjectStatus!
  createdAt: Date!
  updatedAt: Date!
}

type Project implements ProjectInterface {
  id: String!
  userId: String!
  companyId: String!
  companyName: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  country: String!
  targetPrice: String!
  orderQuantities: [Int!]!
  status: ProjectStatus!
  components: [ProjectComponent!]!
  guestEmail: String
  createdAt: Date!
  updatedAt: Date!
}

type PermissionedProject implements ProjectInterface {
  id: String!
  userId: String!
  companyId: String!
  companyName: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  country: String!
  targetPrice: String!
  orderQuantities: [Int!]!
  status: ProjectStatus!
  components: [ProjectComponent!]!
  permission: ProjectPermission!
  guestEmail: String
  createdAt: Date!
  updatedAt: Date!
}

type ProjectChangelog {
  projectId: String!
  changedAt: Date!
  changes: [ProjectPropertyChange!]!
}

type ProjectPropertyChange {
  propertyName: String!
  oldValue: JSON
  newValue: JSON
}

type ProductDimension {
  x: String!
  y: String!
  z: String
}

type PostProcessPrintingNumberOfColors {
  c: String!
  t: String!
}

type PostProcessDetail {
  postProcessName: String!
  isInside: Boolean
  printingMethod: String
  numberOfColors: PostProcessPrintingNumberOfColors
  color: String
  estimatedArea: ProductDimension
  fontSize: String
}

type ProjectComponentSpec {
  id: String!
  productName: String!
  dimension: ProductDimension!
  style: String
  boxStyle: String
  includeArtworkInQuote: Boolean

  # unique attribute for booklet
  numberOfPages: String

  # unique attribute for sticker
  purpose: String
  shape: String

  # unique attribute for corrugate
  flute: String
  # unique attribute for molded fiber
  manufacturingProcess: String

  # common attributes for products that do not have inside/outside difference
  thickness: String
  color: String
  material: String
  materialSource: String
  postProcess: [PostProcessDetail!]
  finish: String

  # common attributes for products that have inside/outside difference
  outsideColor: String
  outsideMaterial: String
  outsideMaterialSource: String
  outsideFinish: String

  insideColor: String
  insideMaterial: String
  insideMaterialSource: String
  insideFinish: String
}

type ProjectComponent {
  id: String!
  projectId: String!
  name: String!
  designs: [ProjectDesign!]
  componentSpec: ProjectComponentSpec!
}

type ProjectComponentChangelog {
  projectComponentId: String!
  changedAt: Date!
  changes: [ProjectComponentPropertyChange!]!
}

type ProjectComponentPropertyChange {
  projectComponentSpecId: String
  propertyName: String!
  oldValue: JSON
  newValue: JSON
}

enum ProjectPermission {
  OWNER
  VIEWER
  EDITOR
}

enum ProjectStatus {
  OPEN
  IN_PROGRESS
  CLOSED
  COMPLETED
  OVERDUE
  INCOMPLETE
}

enum ProjectCreationMode {
  GUIDED
  ADVANCED
}
