input DeleteProjectInput {
  userId: String!
  projectId: String!
}

input DeleteProjectPermissionsInput {
  userIds: [String!]!
  projectId: String!
}

type Mutation {
  deleteProject(projectId: String!): Boolean!
  deleteProjectPermissions(data: DeleteProjectPermissionsInput!): Boolean!
}
