input DeleteProjectInput {
  projectId: String!
}

input DeleteProjectPermissionsInput {
  userIds: [String!]!
  projectId: String!
}

input DeleteProjectDesignInput {
  designId: String!
}

type Mutation {
  deleteProject(data: DeleteProjectInput!): Boolean!
  deleteProjectPermissions(data: DeleteProjectPermissionsInput!): Boolean!
  deleteProjectDesign(data: DeleteProjectDesignInput!): Boolean!
}
