input DeleteProjectInput {
  projectId: String!
}

input DeleteProjectComponentInput {
  componentId: String!
  componentName: String!
}

input DeleteProjectPermissionsInput {
  userIds: [String!]!
  projectId: String!
}

input DeleteProjectDesignInput {
  fileId: String!
}

type Mutation {
  deleteProject(data: DeleteProjectInput!): Boolean!
  deleteProjectPermissions(data: DeleteProjectPermissionsInput!): Boolean!
  deleteProjectDesign(data: DeleteProjectDesignInput!): Boolean!
  # deleteProjectComponents(data: [DeleteProjectComponentInput!]!): Boolean!
}
