scalar JSON

scalar Date

scalar Upload

interface FileInterface {
  fileId: String!
  filename: String!
  url: String!
}

type GenericFile implements FileInterface {
  fileId: String!
  filename: String!
  url: String!
}
