input InviteUserInput {
  email: String!
  userId: String!
}

input CheckUserEmailInput {
  email: String!
}

input UserLoginInput {
  email: String!
  password: String!
}

input RequestToJoinInput {
  companyName: String!
  email: String!
}

input SendPasswordResetLinkInput {
  email: String!
}

input ResetPasswordInput {
  userId: String!
  password: String!
  token: String!
}

type Mutation {
  requestToJoin(data: RequestToJoinInput!): Boolean!
  inviteUsers(data: [InviteUserInput!]!): Boolean!
  sendPasswordResetLink(data: SendPasswordResetLinkInput!): Boolean!
  resetPassword(data: ResetPasswordInput!): Boolean
}

type Query {
  checkUserEmail(data: CheckUserEmailInput!): Boolean!
  login(data: UserLoginInput!): LoggedInUser!
}
