input DeleteProjectBidPermissionsInput {
  userIds: [String!]!
  projectBidId: String!
}

input DeleteBidRemarkInput {
  fileId: String!
}

type Mutation {
  deleteBidRemark(data: DeleteBidRemarkInput!): Boolean!
  deleteProjectBidPermissions(data: DeleteProjectBidPermissionsInput!): Boolean!
}
