interface UserInterface {
  id: String!
  name: String!
  email: String!
  companyId: String!
  isVendor: Boolean!
  power: UserPower!
}

type GenericUser implements UserInterface {
  id: String!
  name: String!
  email: String!
  companyId: String!
  isVendor: Boolean!
  power: UserPower!
  status: UserStatus!
}

# for project/projectBid user info, mainly used when sharing projects/bids
type UserProjectPermission {
  userId: String!
  email: String!
  name: String!
  permission: ProjectPermission!
}

type LoggedInUser implements UserInterface {
  id: String!
  name: String!
  email: String!
  companyId: String!
  isVendor: Boolean!
  power: UserPower!
  token: String!
  chatToken: String!
}

enum UserStatus {
  ACTIVE
  INACTIVE
}

enum UserPower {
  ADMIN
  USER
}
