type User {
  id: String!
  name: String!
  email: String!
  companyId: String!
  isVendor: Boolean!
  isAdmin: Boolean!
  isActive: Boolean!
}

# for project/projectBid user info, mainly used when sharing projects/bids
type UserPermission {
  userId: String!
  email: String!
  name: String!
  permission: ProjectPermission!
}

type LoggedInUser {
  id: String!
  name: String!
  email: String!
  companyId: String!
  isVendor: Boolean!
  isAdmin: Boolean!
  token: String!
  notificationToken: String!
  chatToken: String!
  isActive: Boolean!
}

input UserLoginInput {
  email: String!
  password: String!
}
