input SearchVendorCompanyInput {
  userInput: String!
  countries: [String!]
  factoryLocations: [String!]
  moqMin: String
  moqMax: String
  leadTime: String
}

type VendorSearchHighlight {
  products: [String]
  name: [String]
}

type VendorSearchItem {
  vendor: VendorOverview!
  highlight: VendorSearchHighlight!
}

type Query {
  searchVendorCompanies(data: SearchVendorCompanyInput!): [VendorSearchItem!]!
}
