input SearchVendorCompanyInput {
  userInput: String!
  countries: [String!]
  factoryLocations: [String!]
  moqMin: String
  moqMax: String
  leadTime: String
}

type Query {
  searchVendorCompanies(data: SearchVendorCompanyInput!): [VendorOverview!]!
}
