input SearchCustomerProjectInput {
  userInput: String!
  targetPrice: String
  orderQuantities: [String!]
  deliveryDate: String
}

type Query {
  searchCustomerProjects(data: SearchCustomerProjectInput!): [ProjectOverview!]!
}
