input SearchCustomerProjectInput {
  userInput: String!
  targetPriceRange: [String!]
  orderQuantities: [String!]
  deliveryDate: String
  countries: [String!]
}

input SearchProductsInput {
  searchText: String!
}

input SearchCategoriesInput {
  searchText: String!
}

type Query {
  searchCustomerProjects(data: SearchCustomerProjectInput!): [ProjectOverview!]!
  searchProducts(data: SearchProductsInput): [String!]!
  searchCategories(data: SearchCategoriesInput): [Category!]!
}
