input GetAllUsersWithinCompanyInput {
  companyId: String!
}

input GetUserInput {
  userId: String!
}
type Query {
  getAllUsersWithinCompany(data: GetAllUsersWithinCompanyInput!): [User!]!
  getUser(data: GetUserInput!): User!
}
