input GetAllUsersWithinCompanyInput {
  companyId: String!
}

input GetUserInput {
  userId: String!
}
type Query {
  getAllUsersWithinCompany(
    data: GetAllUsersWithinCompanyInput!
  ): [GenericUser!]!
  getUser(data: GetUserInput!): GenericUser!
}
