enum ProjectPermission {
  OWNER
  VIEWER
  EDITOR
}

enum ProjectStatus {
  OPEN
  IN_PROGRESS
  CLOSED
}

enum BidStatus {
  OPEN
  ACCEPTED
  REJECTED
}

enum CompanyPermission {
  ADMIN
  USER
}

enum PlanTier {
  PREMIUM
  BUSINESS
}

enum CompanySize {
  XS
  S
  M
  L
}
