input GetCustomerProjectsInput {
  userId: String!
  permissions: [ProjectPermission!]
}

input GetCustomerDetailInput {
  companyId: String!
}

input GetCustomerProjectInput {
  userId: String!
  projectId: String!
}

input GetCustomerPosInput {
  userId: String!
}

input GetPurchaseOrderInput {
  projectId: String!
  projectBidId: String!
}

type Query {
  getCustomerDetail(data: GetCustomerDetailInput!): CustomerDetail!
  getCustomerProject(data: GetCustomerProjectInput!): CustomerProject!
  getCustomerProjects(
    data: GetCustomerProjectsInput!
  ): [CustomerProjectOverview!]!
  getPurchaseOrder(data: GetPurchaseOrderInput!): PurchaseOrder
  getCustomerPos(data: GetCustomerPosInput!): [CustomerPo!]!
}
