type Query {
  getCustomerDetail(companyId: String!): CustomerDetail!
  getCustomerProject(data: GetProjectInput!): CustomerProject!
  getCustomerProjects(userId: String!): [CustomerProject!]!
  searchCustomerProjects(searchInput: SearchProjectInput!): [ProjectOverview!]!
  getEditableCustomerDetail(companyId: String!): EditableCustomerDetail!
}
