input CreateCustomerInput {
  name: String!
  contactEmail: String!
  logo: String
  phone: String!
  fax: String
  country: String!
  planId: String!
  isActive: Boolean!
  isVendor: Boolean!
  isVerified: Boolean!
  companyUrl: String
  userEmail: String!
  stripeCustomerInfo: StripeCustomerInfo!
}

input CreatePurchaseOrderInput {
  purchaseOrderId: String!
  projectId: String!
  projectBidId: String!
}

type Mutation {
  createCustomer(data: CreateCustomerInput!): Boolean!
  createCustomerSubscription(
    priceId: String!
    stripeCustomerId: String!
  ): StripeSubscription!
  createPurchaseOrder(data: CreatePurchaseOrderInput!): Boolean!
}
