type CustomerOverview {
  id: String!
  name: String!
  contactEmail: String!
  logo: String
  country: String!
  isVerified: Boolean!
}

type CustomerProjectOverview {
  id: String!
  userId: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  targetPrice: Int!
  orderQuantities: [Int!]!
  status: String!
  permission: ProjectPermission!
  createdAt: String!
  updatedAt: String!
}

# to be augmented later when customer have more attributes
type CustomerDetail {
  id: String!
  name: String!
  contactEmail: String!
  phone: String!
  logo: String
  country: String!
  isActive: Boolean!
  companyUrl: String
  fax: String
  isVerified: Boolean!
}

type CustomerProject {
  id: String!
  userId: String!
  companyId: String!
  creationMode: ProjectCreationMode!
  companyName: String!
  name: String!
  category: String!
  totalWeight: String!
  deliveryDate: String!
  deliveryAddress: String!
  targetPrice: Int!
  orderQuantities: [Int!]!
  comments: String!
  status: String!
  permission: ProjectPermission!
  components: [ProjectComponent!]!
  bids: [ProjectBid!]
  createdAt: String!
  updatedAt: String!
}
