type PermissionedProjectBid {
  id: String!
  userId: String!
  projectId: String!
  companyId: String!
  components: [ProjectBidComponent!]!
  permission: ProjectPermission!
  status: BidStatus!
  createdAt: Date!
  updatedAt: Date!
}

type ProjectBid {
  id: String!
  userId: String!
  companyId: String!
  projectId: String!
  comments: String!
  components: [ProjectBidComponent!]!
  status: BidStatus!
  createdAt: Date!
  updatedAt: Date!
}

type ProjectBidComponent {
  id: String!
  projectBidId: String!
  projectComponentId: String!
  quantityPrices: [QuantityPrice!]!
  samplingFee: Int!
  toolingFee: Int
}

type QuantityPrice {
  quantity: Int!
  price: String!
}

enum BidStatus {
  OPEN
  ACCEPTED
  PO_ISSUED
  PO_ACCEPTED
  INVOICE_ISSUED
  INVOICE_ACCEPTED
  REJECTED
  OUTDATED
  EXPIRED
}
