input GetProjectDetailInput {
  projectId: String!
}

input GetProjectUsersInput {
  projectId: String!
}

type Query {
  getProjectUsers(data: GetProjectUsersInput!): [UserProjectPermission!]!

  getProjectDetail(data: GetProjectDetailInput!): Project
}
