input GetProjectDetailInput {
  projectId: String!
}

input GetProjectUsersInput {
  projectId: String!
}

input GetProjectChangelogInput {
  projectId: String!
}

input GetProjectComponentChangelogInput {
  projectComponentIds: [String!]!
}

input GetGuestProjectDetailInput {
  projectId: String!
}

input GetSearchProjectDetailInput {
  projectId: String!
  companyId: String!
}

type Query {
  getProjectUsers(data: GetProjectUsersInput!): [UserProjectPermission!]!

  getProjectDetail(data: GetProjectDetailInput!): Project

  getProjectChangelog(data: GetProjectChangelogInput!): [ProjectChangelog!]!

  getProjectComponentChangelog(
    data: GetProjectComponentChangelogInput!
  ): [[ProjectComponentChangelog!]!]!

  getGuestProjectDetail(data: GetGuestProjectDetailInput!): Project

  getSearchProjectDetail(data: GetSearchProjectDetailInput!): Project
}
