type CompanyPlan {
  id: String!
  planId: String!
  companyId: String!
}
type CompanyPlanDetail {
  tier: PlanTier!
  price: Int!
  billingFrequency: String!
  memberSince: String!
  subscriptionStartDate: String!
  subscriptionEndDate: String!
  trialStartDate: String
  trialEndDate: String
}
type PermissionedCompany {
  id: String!
  name: String!
  contactEmail: String!
  logo: String!
  phone: String!
  fax: String!
  country: String!
  planInfo: CompanyPlan!
  isActive: Boolean!
  isVendor: Boolean!
  isVerified: Boolean!
  leadTime: Int
  locations: [String!]
  moq: Int
  products: [String!]
  isAdmin: Boolean!
  companyUrl: String!
  createdAt: Date!
  updatedAt: Date!
}

type CompanyDetail {
  id: String!
  name: String!
  contactEmail: String!
  logo: String
  phone: String!
  fax: String
  country: String!
  isActive: Boolean!
  isVendor: Boolean!
  isVerified: Boolean!
  companyUrl: String

  locations: [String!]
  products: [String!]
  moq: String
  leadTime: Int

  createdAt: Date!
  updatedAt: Date!
}

enum CompanyPermission {
  ADMIN
  USER
}

enum CompanySize {
  XS
  S
  M
  L
}
