input CreateStripeCustomerInStripeInput {
  email: String!
  priceId: String!
}

type Mutation {
  createStripeCustomerInStripe(
    data: CreateStripeCustomerInStripeInput!
  ): StripePaymentIntent!
}
