input CreateStripeCustomerInStripeForCustomerInput {
  companyId: String!
  priceId: String!
}

input CreateStripeCustomerInStripeForVendorInput {
  email: String!
  perUserPriceId: String!
  subscriptionPriceId: String!
}

type Mutation {
  createStripeCustomerInStripeForCustomer(
    data: CreateStripeCustomerInStripeForCustomerInput!
  ): StripePaymentIntent!
  createStripeCustomerInStripeForVendor(
    data: CreateStripeCustomerInStripeForVendorInput!
  ): StripePaymentIntent!
}
