input UpdateCompanyPlanInput {
  planId: String!
  companyId: String!
}

input UpdateCompanyStatusInput {
  companyId: String!
  isActive: Boolean!
}

input UpdateCompanyPlanSubscriptionInfoInput {
  subscriptionId: String!
}

type Mutation {
  updateCompanyPlan(data: UpdateCompanyPlanInput!): Boolean!
  updateCompanyStatus(data: UpdateCompanyStatusInput!): Boolean!
  updateCompanyPlanSubscriptionInfo(
    data: UpdateCompanyPlanSubscriptionInfoInput!
  ): Boolean!
}
