input UpdateProjectBidInput {
  projectId: String!
  projectBidId: String!
  bidRemarkFileId: String
}

input UpdateProjectBidComponentInput {
  bidComponentId: String!
  quantityPrices: [QuantityPriceInput!]!
  samplingFee: Int!
  toolingFee: Int
}

input UpdateProjectBidPermissionsInput {
  viewers: UpdateProjectBidPermissionsInputData!
  editors: UpdateProjectBidPermissionsInputData!
}

input UpdateProjectBidPermissionsInputData {
  userIds: [String]!
  projectId: String!
  projectBidId: String!
  permission: ProjectPermission!
}

input ResubmitProjectBidInput {
  projectBidId: String!
}

type Mutation {
  updateProjectBidPermissions(data: UpdateProjectBidPermissionsInput!): Boolean!
  updateProjectBid(data: UpdateProjectBidInput!): Boolean!
  updateProjectBidComponents(data: [UpdateProjectBidComponentInput!]!): Boolean!
  resubmitProjectBid(data: ResubmitProjectBidInput!): Boolean!
}
