input GetProjectBidUsersInput {
  projectBidId: String!
}

input GetProjectBidInput {
  companyId: String!
  projectId: String!
}

input GetProjectBidsForPoInput {
  projectId: String!
}

type Query {
  getProjectBidUsers(data: GetProjectBidUsersInput!): [UserProjectPermission!]!
  getProjectBid(data: GetProjectBidInput!): ProjectBid
  getProjectBidsForPo(data: GetProjectBidsForPoInput!): [ProjectBidForPo!]!
}
