input CreateProjectComponentSpecInput {
  productName: String!
  dimension: String!
}

input CreateProjectComponentInput {
  name: String!
  componentSpec: CreateProjectComponentSpecInput!
}

input CreateProjectInput {
  userId: String!
  name: String!
  designId: String
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  comments: String!
  components: [CreateProjectComponentInput!]!
}

type Mutation {
  createProject(data: CreateProjectInput!): Boolean!
}
