input CreateProjectComponentInput {
  name: String!
  materials: [String!]!
  dimension: String!
  postProcess: String!
}

input CreateProjectInput {
  userId: String!
  name: String!
  designId: String
  deliveryDate: String!
  deliveryAddress: String!
  budget: Int!
  comments: String!
  components: [CreateProjectComponentInput!]!
}

type Mutation {
  createProject(data: CreateProjectInput!): Boolean!
}
