name: Build Docker Image
run-name: Building ${{ github.ref_name }}
on: workflow_dispatch
jobs:
  Generate-Build-Tag:
    uses: ./.github/workflows/generate-build-tag.yml
  Build-and-Push-Docker-Image-to-ECR:
    runs-on: ubuntu-latest
    needs: Generate-Build-Tag
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up QEMU for docker-buildx
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx for ARM builds
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Image
        env:
          buildtag: ${{ needs.Generate-Build-Tag.outputs.build-tag }}
        run: |
          docker-buildx build --push -t 878684683110.dkr.ecr.us-east-1.amazonaws.com/zax-exchange-webservice-repository:${buildtag} .