name: Build and Push Docker Image
run-name: ${{ github.actor }} is Building and Pushing Docker image to ECR
on: workflow_dispatch
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate build tag
        id: tag_step
        run: |
          echo "Generating build tag pipeline on branch ${{ github.ref }}"
          gittag=${{github.sha}}
          echo "  Found hash ${gittag}"
          version=$(npm pkg get version | tr -d '"')
          echo "  Found package version ${version}"
          buildtag="zax-webservice-${version}-${gittag}"
          echo "Final buildtag ${buildtag}"
          echo "buildtag=$buildtag" >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and Push Image
        env: 
          buildtag: ${{ steps.tag_step.outputs.buildtag }}
        run: |
          docker build -t ${buildtag} .
          docker tag ${buildtag} 878684683110.dkr.ecr.us-east-1.amazonaws.com/zax-exchange-webapp-repository:${buildtag}
          docker push 878684683110.dkr.ecr.us-east-1.amazonaws.com/zax-exchange-webapp-repository:${buildtag}