name: Set verion to this build
run-name: ${{ github.actor }} is Setting Version and Pushing Image to EKS
on:
  workflow_dispatch:
    inputs:
      deploymentEnvironment:
        description: 'dev|stg|prod'
        required: true
        type: string
        options:
        - stg
jobs:
  Generate-Build-Tag:
    uses: ./.github/workflows/generate-build-tag.yml
    runs-on: ubuntu-latest
    steps:
      - name: Update tag 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  Set-Version-in-CDK-Configuration:
    uses: Zax-Exchange/zax-cdks/.github/workflows/set-version.yml@master
    needs: Generate-Build-Tag
    with: 
      deploymentEnvironment: ${{ inputs.deploymentEnvironment }}
      varName: ZAX_WEBSERVICE_DEPLOY_IMAGE_TAG
      varValue: ${{ needs.Generate-Build-Tag.outputs.buildtag }}
    secrets: inherit
  Run-CDK-and-Deploy:
    uses: Zax-Exchange/zax-cdks/.github/workflows/cdk-deploy.yml@master
    with: 
      deploymentEnvironment: ${{ inputs.deploymentEnvironment }}
    secrets: inherit