name: Deploy Docker Image
run-name: ${{ github.actor }} is Setting Version and Pushing Image to EKS
on:
  workflow_dispatch:
    inputs:
      deploymentEnvironment:
        description: 'dev|stg|prod'
        required: true
        type: string
        options:
        - stg
jobs:
  Generate-Build-Tag:
    uses: ./.github/workflows/generate-build-tag.yml
  Set-Version-in-CDK-Configuration:
    uses: Zax-Exchange/zax-cdks/.github/workflows/set-version.yml@master
    needs: Generate-Build-Tag
    with: 
      deploymentEnvironment: ${{ inputs.deploymentEnvironment }}
      varName: ZAX_WEBSERVICE_DEPLOY_IMAGE_TAG
      varValue: ${{ needs.Generate-Build-Tag.outputs.build-tag }}
    secrets: inherit
  Run-CDK-and-Deploy:
    uses: Zax-Exchange/zax-cdks/.github/workflows/cdk-deploy.yml@master
    needs: Set-Version-in-CDK-Configuration
    with: 
      deploymentEnvironment: ${{ inputs.deploymentEnvironment }}
    secrets: inherit