input UpdateCustomerInfoInput {
  companyId: String!
  name: String!
  contactEmail: String!
  logo: String
  phone: String!
  fax: String
  country: String!
  companyUrl: String
}

type Mutation {
  updateCustomerInfo(data: UpdateCustomerInfoInput!): Boolean!
}
